name: Container Image Scan

on:
    workflow_dispatch:

jobs:
    trivy-scan:
        name: Trivy Container Image Scan
        runs-on: ubuntu-latest

        steps:
            - name: git checkout
              uses: actions/checkout@v7
            
            - name: Build JLink Docker Image
              run: | 
                docker build -f Dockerfile.jlink -t three-tier-app:jlink .

            - name: Run Trivy Image Scan
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                image-ref: three-tier-app:jlink
                format: table
                exit-code: 1
                ignore-unfixed: true
                vuln-type: 'os,library'
                severity: 'CRITICAL,HIGH'

            - name: Run Trivy Scan - SARIF Report
              if: always()
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                image-ref: three-tier-app:jlink
                format: sarif
                output: trivy-results.sarif
                ignore-unfixed: true
                vuln-type: 'os,library'
                severity: 'CRITICAL,HIGH'

            - name: Upload Trivy Report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: trivy-container-scan-report
                path: trivy-results.sarif
