name: Dockerfile Scan

on:
  workflow_call:

jobs:
    hadolint:
        name: Hadolint Dockerfile Scan
        runs-on: ubuntu-latest

        steps:
            - name: git checkout
              uses: actions/checkout@v7
              with:
                fetch-depth: 0

            - name: scan Dockerfile 
              uses: hadolint/hadolint-action@v3.2.0
              with:
                dockerfile: Dockerfile
                failure-threshold: warning

            - name: Scan Dockerfile.multistage
              uses: hadolint/hadolint-action@v3.2.0
              with:
                dockerfile: Dockerfile.multistage
                failure-threshold: warning

            - name: Scan Dockerfile.jlink
              uses: hadolint/hadolint-action@v3.2.0
              with:
                dockerfile: Dockerfile.jlink
                failure-threshold: warning
